# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T02:43:05+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class BuildBazelRemoteExecutionV2CommandEnvironmentVariable(BaseModel):
    name: Optional[str] = Field(None, description='The variable name.')
    value: Optional[str] = Field(None, description='The variable value.')


class BuildBazelRemoteExecutionV2Digest(BaseModel):
    hash: Optional[str] = Field(
        None,
        description='The hash. In the case of SHA-256, it will always be a lowercase hex string exactly 64 characters long.',
    )
    sizeBytes: Optional[str] = Field(
        None, description='The size of the blob, in bytes.'
    )


class BuildBazelRemoteExecutionV2DirectoryNode(BaseModel):
    digest: Optional[BuildBazelRemoteExecutionV2Digest] = Field(
        None,
        description='The digest of the Directory object represented. See Digest for information about how to take the digest of a proto message.',
    )
    name: Optional[str] = Field(None, description='The name of the directory.')


class Stage(Enum):
    UNKNOWN = 'UNKNOWN'
    CACHE_CHECK = 'CACHE_CHECK'
    QUEUED = 'QUEUED'
    EXECUTING = 'EXECUTING'
    COMPLETED = 'COMPLETED'


class BuildBazelRemoteExecutionV2ExecutedActionMetadata(BaseModel):
    auxiliaryMetadata: Optional[List[Dict[str, Any]]] = Field(
        None,
        description='Details that are specific to the kind of worker used. For example, on POSIX-like systems this could contain a message with getrusage(2) statistics.',
    )
    executionCompletedTimestamp: Optional[str] = Field(
        None, description='When the worker completed executing the action command.'
    )
    executionStartTimestamp: Optional[str] = Field(
        None, description='When the worker started executing the action command.'
    )
    inputFetchCompletedTimestamp: Optional[str] = Field(
        None, description='When the worker finished fetching action inputs.'
    )
    inputFetchStartTimestamp: Optional[str] = Field(
        None, description='When the worker started fetching action inputs.'
    )
    outputUploadCompletedTimestamp: Optional[str] = Field(
        None, description='When the worker finished uploading action outputs.'
    )
    outputUploadStartTimestamp: Optional[str] = Field(
        None, description='When the worker started uploading action outputs.'
    )
    queuedTimestamp: Optional[str] = Field(
        None, description='When was the action added to the queue.'
    )
    virtualExecutionDuration: Optional[str] = Field(
        None,
        description='New in v2.3: the amount of time the worker spent executing the action command, potentially computed using a worker-specific virtual clock. The virtual execution duration is only intended to cover the "execution" of the specified action and not time in queue nor any overheads before or after execution such as marshalling inputs/outputs. The server SHOULD avoid including time spent the client doesn\'t have control over, and MAY extend or reduce the execution duration to account for delays or speedups that occur during execution itself (e.g., lazily loading data from the Content Addressable Storage, live migration of virtual machines, emulation overhead). The method of timekeeping used to compute the virtual execution duration MUST be consistent with what is used to enforce the Action\'s `timeout`. There is no relationship between the virtual execution duration and the values of `execution_start_timestamp` and `execution_completed_timestamp`.',
    )
    worker: Optional[str] = Field(
        None, description='The name of the worker which ran the execution.'
    )
    workerCompletedTimestamp: Optional[str] = Field(
        None, description='When the worker completed the action, including all stages.'
    )
    workerStartTimestamp: Optional[str] = Field(
        None, description='When the worker received the action.'
    )


class BuildBazelRemoteExecutionV2LogFile(BaseModel):
    digest: Optional[BuildBazelRemoteExecutionV2Digest] = Field(
        None, description='The digest of the log contents.'
    )
    humanReadable: Optional[bool] = Field(
        None,
        description='This is a hint as to the purpose of the log, and is set to true if the log is human-readable text that can be usefully displayed to a user, and false otherwise. For instance, if a command-line client wishes to print the server logs to the terminal for a failed action, this allows it to avoid displaying a binary file.',
    )


class BuildBazelRemoteExecutionV2NodeProperty(BaseModel):
    name: Optional[str] = Field(None, description='The property name.')
    value: Optional[str] = Field(None, description='The property value.')


class BuildBazelRemoteExecutionV2OutputDirectory(BaseModel):
    isTopologicallySorted: Optional[bool] = Field(
        None,
        description='If set, consumers MAY make the following assumptions about the directories contained in the the Tree, so that it may be instantiated on a local file system by scanning through it sequentially: - All directories with the same binary representation are stored exactly once. - All directories, apart from the root directory, are referenced by at least one parent directory. - Directories are stored in topological order, with parents being stored before the child. The root directory is thus the first to be stored. Additionally, the Tree MUST be encoded as a stream of records, where each record has the following format: - A tag byte, having one of the following two values: - (1 << 3) | 2 == 0x0a: First record (the root directory). - (2 << 3) | 2 == 0x12: Any subsequent records (child directories). - The size of the directory, encoded as a base 128 varint. - The contents of the directory, encoded as a binary serialized Protobuf message. This encoding is a subset of the Protobuf wire format of the Tree message. As it is only permitted to store data associated with field numbers 1 and 2, the tag MUST be encoded as a single byte. More details on the Protobuf wire format can be found here: https://developers.google.com/protocol-buffers/docs/encoding It is recommended that implementations using this feature construct Tree objects manually using the specification given above, as opposed to using a Protobuf library to marshal a full Tree message. As individual Directory messages already need to be marshaled to compute their digests, constructing the Tree object manually avoids redundant marshaling.',
    )
    path: Optional[str] = Field(
        None,
        description='The full path of the directory relative to the working directory. The path separator is a forward slash `/`. Since this is a relative path, it MUST NOT begin with a leading forward slash. The empty string value is allowed, and it denotes the entire working directory.',
    )
    treeDigest: Optional[BuildBazelRemoteExecutionV2Digest] = Field(
        None,
        description="The digest of the encoded Tree proto containing the directory's contents.",
    )


class BuildBazelRemoteExecutionV2PlatformProperty(BaseModel):
    name: Optional[str] = Field(None, description='The property name.')
    value: Optional[str] = Field(None, description='The property value.')


class BuildBazelRemoteExecutionV2ToolDetails(BaseModel):
    toolName: Optional[str] = Field(None, description='Name of the tool, e.g. bazel.')
    toolVersion: Optional[str] = Field(
        None, description='Version of the tool used for the request, e.g. 5.0.3.'
    )


class GoogleDevtoolsRemotebuildbotCommandDurations(BaseModel):
    casRelease: Optional[str] = Field(
        None, description='The time spent to release the CAS blobs used by the task.'
    )
    cmWaitForAssignment: Optional[str] = Field(
        None,
        description='The time spent waiting for Container Manager to assign an asynchronous container for execution.',
    )
    dockerPrep: Optional[str] = Field(
        None,
        description='The time spent preparing the command to be run in a Docker container (includes pulling the Docker image, if necessary).',
    )
    dockerPrepStartTime: Optional[str] = Field(
        None, description='The timestamp when docker preparation begins.'
    )
    download: Optional[str] = Field(
        None,
        description='The time spent downloading the input files and constructing the working directory.',
    )
    downloadStartTime: Optional[str] = Field(
        None, description='The timestamp when downloading the input files begins.'
    )
    execStartTime: Optional[str] = Field(
        None, description='The timestamp when execution begins.'
    )
    execution: Optional[str] = Field(
        None,
        description='The time spent executing the command (i.e., doing useful work).',
    )
    isoPrepDone: Optional[str] = Field(
        None,
        description='The timestamp when preparation is done and bot starts downloading files.',
    )
    overall: Optional[str] = Field(
        None, description='The time spent completing the command, in total.'
    )
    stderr: Optional[str] = Field(
        None, description='The time spent uploading the stderr logs.'
    )
    stdout: Optional[str] = Field(
        None, description='The time spent uploading the stdout logs.'
    )
    upload: Optional[str] = Field(
        None, description='The time spent uploading the output files.'
    )
    uploadStartTime: Optional[str] = Field(
        None, description='The timestamp when uploading the output files begins.'
    )


class CmUsage(Enum):
    CONFIG_NONE = 'CONFIG_NONE'
    CONFIG_MATCH = 'CONFIG_MATCH'
    CONFIG_MISMATCH = 'CONFIG_MISMATCH'


class OutputLocation(Enum):
    LOCATION_UNDEFINED = 'LOCATION_UNDEFINED'
    LOCATION_NONE = 'LOCATION_NONE'
    LOCATION_EXEC_ROOT_RELATIVE = 'LOCATION_EXEC_ROOT_RELATIVE'
    LOCATION_WORKING_DIR_RELATIVE = 'LOCATION_WORKING_DIR_RELATIVE'
    LOCATION_EXEC_ROOT_AND_WORKING_DIR_RELATIVE = (
        'LOCATION_EXEC_ROOT_AND_WORKING_DIR_RELATIVE'
    )
    LOCATION_EXEC_ROOT_RELATIVE_OUTPUT_OUTSIDE_WORKING_DIR = (
        'LOCATION_EXEC_ROOT_RELATIVE_OUTPUT_OUTSIDE_WORKING_DIR'
    )
    LOCATION_EXEC_ROOT_AND_WORKING_DIR_RELATIVE_OUTPUT_OUTSIDE_WORKING_DIR = (
        'LOCATION_EXEC_ROOT_AND_WORKING_DIR_RELATIVE_OUTPUT_OUTSIDE_WORKING_DIR'
    )


class GoogleDevtoolsRemotebuildbotCommandEvents(BaseModel):
    cmUsage: Optional[CmUsage] = Field(
        None,
        description='Indicates if and how Container Manager is being used for task execution.',
    )
    dockerCacheHit: Optional[bool] = Field(
        None,
        description='Indicates whether we are using a cached Docker image (true) or had to pull the Docker image (false) for this command.',
    )
    dockerImageName: Optional[str] = Field(None, description='Docker Image name.')
    inputCacheMiss: Optional[float] = Field(
        None, description='The input cache miss ratio.'
    )
    numErrors: Optional[str] = Field(None, description='The number of errors reported.')
    numWarnings: Optional[str] = Field(
        None, description='The number of warnings reported.'
    )
    outputLocation: Optional[OutputLocation] = Field(
        None,
        description='Indicates whether output files and/or output directories were found relative to the execution root or to the user provided work directory or both or none.',
    )
    usedAsyncContainer: Optional[bool] = Field(
        None,
        description='Indicates whether an asynchronous container was used for execution.',
    )


class Code(Enum):
    OK = 'OK'
    INVALID_ARGUMENT = 'INVALID_ARGUMENT'
    DEADLINE_EXCEEDED = 'DEADLINE_EXCEEDED'
    NOT_FOUND = 'NOT_FOUND'
    PERMISSION_DENIED = 'PERMISSION_DENIED'
    INTERNAL = 'INTERNAL'
    ABORTED = 'ABORTED'
    FAILED_PRECONDITION = 'FAILED_PRECONDITION'
    CLEANUP_ERROR = 'CLEANUP_ERROR'
    DOWNLOAD_INPUTS_ERROR = 'DOWNLOAD_INPUTS_ERROR'
    UNKNOWN = 'UNKNOWN'
    UPLOAD_OUTPUTS_ERROR = 'UPLOAD_OUTPUTS_ERROR'
    UPLOAD_OUTPUTS_BYTES_LIMIT_EXCEEDED = 'UPLOAD_OUTPUTS_BYTES_LIMIT_EXCEEDED'
    DOCKER_LOGIN_ERROR = 'DOCKER_LOGIN_ERROR'
    DOCKER_IMAGE_PULL_ERROR = 'DOCKER_IMAGE_PULL_ERROR'
    DOCKER_IMAGE_EXIST_ERROR = 'DOCKER_IMAGE_EXIST_ERROR'
    DUPLICATE_INPUTS = 'DUPLICATE_INPUTS'
    DOCKER_IMAGE_PERMISSION_DENIED = 'DOCKER_IMAGE_PERMISSION_DENIED'
    DOCKER_IMAGE_NOT_FOUND = 'DOCKER_IMAGE_NOT_FOUND'
    WORKING_DIR_NOT_FOUND = 'WORKING_DIR_NOT_FOUND'
    WORKING_DIR_NOT_IN_BASE_DIR = 'WORKING_DIR_NOT_IN_BASE_DIR'
    DOCKER_UNAVAILABLE = 'DOCKER_UNAVAILABLE'
    NO_CUDA_CAPABLE_DEVICE = 'NO_CUDA_CAPABLE_DEVICE'
    REMOTE_CAS_DOWNLOAD_ERROR = 'REMOTE_CAS_DOWNLOAD_ERROR'
    REMOTE_CAS_UPLOAD_ERROR = 'REMOTE_CAS_UPLOAD_ERROR'
    LOCAL_CASPROXY_NOT_RUNNING = 'LOCAL_CASPROXY_NOT_RUNNING'
    DOCKER_CREATE_CONTAINER_ERROR = 'DOCKER_CREATE_CONTAINER_ERROR'
    DOCKER_INVALID_ULIMIT = 'DOCKER_INVALID_ULIMIT'
    DOCKER_UNKNOWN_RUNTIME = 'DOCKER_UNKNOWN_RUNTIME'
    DOCKER_UNKNOWN_CAPABILITY = 'DOCKER_UNKNOWN_CAPABILITY'
    DOCKER_UNKNOWN_ERROR = 'DOCKER_UNKNOWN_ERROR'
    DOCKER_CREATE_COMPUTE_SYSTEM_ERROR = 'DOCKER_CREATE_COMPUTE_SYSTEM_ERROR'
    DOCKER_PREPARELAYER_ERROR = 'DOCKER_PREPARELAYER_ERROR'
    DOCKER_INCOMPATIBLE_OS_ERROR = 'DOCKER_INCOMPATIBLE_OS_ERROR'
    DOCKER_CREATE_RUNTIME_FILE_NOT_FOUND = 'DOCKER_CREATE_RUNTIME_FILE_NOT_FOUND'
    DOCKER_CREATE_RUNTIME_PERMISSION_DENIED = 'DOCKER_CREATE_RUNTIME_PERMISSION_DENIED'
    DOCKER_CREATE_PROCESS_FILE_NOT_FOUND = 'DOCKER_CREATE_PROCESS_FILE_NOT_FOUND'
    DOCKER_CREATE_COMPUTE_SYSTEM_INCORRECT_PARAMETER_ERROR = (
        'DOCKER_CREATE_COMPUTE_SYSTEM_INCORRECT_PARAMETER_ERROR'
    )
    DOCKER_TOO_MANY_SYMBOLIC_LINK_LEVELS = 'DOCKER_TOO_MANY_SYMBOLIC_LINK_LEVELS'
    LOCAL_CONTAINER_MANAGER_NOT_RUNNING = 'LOCAL_CONTAINER_MANAGER_NOT_RUNNING'
    DOCKER_IMAGE_VPCSC_PERMISSION_DENIED = 'DOCKER_IMAGE_VPCSC_PERMISSION_DENIED'
    WORKING_DIR_NOT_RELATIVE = 'WORKING_DIR_NOT_RELATIVE'
    DOCKER_MISSING_CONTAINER = 'DOCKER_MISSING_CONTAINER'
    DOCKER_MISSING_BLOB_IN_IMAGE = 'DOCKER_MISSING_BLOB_IN_IMAGE'
    DOCKER_INVALID_VOLUME = 'DOCKER_INVALID_VOLUME'
    DOCKER_CREATE_RUNTIME_CANNOT_MOUNT_TO_PROC = (
        'DOCKER_CREATE_RUNTIME_CANNOT_MOUNT_TO_PROC'
    )
    DOCKER_START_RUNTIME_FILE_NOT_FOUND = 'DOCKER_START_RUNTIME_FILE_NOT_FOUND'
    DOCKER_CREATE_INVALID_LAYERCHAIN_JSON = 'DOCKER_CREATE_INVALID_LAYERCHAIN_JSON'
    INCOMPATIBLE_CUDA_VERSION = 'INCOMPATIBLE_CUDA_VERSION'
    LOCAL_WORKER_MANAGER_NOT_RUNNING = 'LOCAL_WORKER_MANAGER_NOT_RUNNING'


class GoogleDevtoolsRemotebuildbotCommandStatus(BaseModel):
    code: Optional[Code] = Field(None, description='The status code.')
    message: Optional[str] = Field(None, description='The error message.')


class GoogleDevtoolsRemotebuildbotResourceUsageIOStats(BaseModel):
    readBytesCount: Optional[str] = None
    readCount: Optional[str] = None
    readTimeMs: Optional[str] = None
    writeBytesCount: Optional[str] = None
    writeCount: Optional[str] = None
    writeTimeMs: Optional[str] = None


class GoogleDevtoolsRemotebuildbotResourceUsageStat(BaseModel):
    total: Optional[str] = None
    used: Optional[str] = None


class GoogleDevtoolsRemotebuildexecutionAdminV1alphaAcceleratorConfig(BaseModel):
    acceleratorCount: Optional[str] = Field(
        None, description='The number of guest accelerator cards exposed to each VM.'
    )
    acceleratorType: Optional[str] = Field(
        None,
        description='The type of accelerator to attach to each VM, e.g. "nvidia-tesla-k80" for nVidia Tesla K80.',
    )


class GoogleDevtoolsRemotebuildexecutionAdminV1alphaAutoscale(BaseModel):
    maxSize: Optional[str] = Field(
        None,
        description='The maximal number of workers. Must be equal to or greater than min_size.',
    )
    minSize: Optional[str] = Field(
        None, description='The minimal number of workers. Must be greater than 0.'
    )


class GoogleDevtoolsRemotebuildexecutionAdminV1alphaDeleteInstanceRequest(BaseModel):
    name: Optional[str] = Field(
        None,
        description='Required. Name of the instance to delete. Format: `projects/[PROJECT_ID]/instances/[INSTANCE_ID]`.',
    )


class GoogleDevtoolsRemotebuildexecutionAdminV1alphaDeleteWorkerPoolRequest(BaseModel):
    name: Optional[str] = Field(
        None,
        description='Name of the worker pool to delete. Format: `projects/[PROJECT_ID]/instances/[INSTANCE_ID]/workerpools/[POOL_ID]`.',
    )


class ActionHermeticity(Enum):
    ACTION_HERMETICITY_UNSPECIFIED = 'ACTION_HERMETICITY_UNSPECIFIED'
    ACTION_HERMETICITY_OFF = 'ACTION_HERMETICITY_OFF'
    ACTION_HERMETICITY_ENFORCED = 'ACTION_HERMETICITY_ENFORCED'
    ACTION_HERMETICITY_BEST_EFFORT = 'ACTION_HERMETICITY_BEST_EFFORT'


class ActionIsolation(Enum):
    ACTION_ISOLATION_UNSPECIFIED = 'ACTION_ISOLATION_UNSPECIFIED'
    ACTION_ISOLATION_OFF = 'ACTION_ISOLATION_OFF'
    ACTION_ISOLATION_ENFORCED = 'ACTION_ISOLATION_ENFORCED'


class LinuxExecution(Enum):
    LINUX_EXECUTION_UNSPECIFIED = 'LINUX_EXECUTION_UNSPECIFIED'
    LINUX_EXECUTION_FORBIDDEN = 'LINUX_EXECUTION_FORBIDDEN'
    LINUX_EXECUTION_UNRESTRICTED = 'LINUX_EXECUTION_UNRESTRICTED'
    LINUX_EXECUTION_HARDENED_GVISOR = 'LINUX_EXECUTION_HARDENED_GVISOR'
    LINUX_EXECUTION_HARDENED_GVISOR_OR_TERMINAL = (
        'LINUX_EXECUTION_HARDENED_GVISOR_OR_TERMINAL'
    )


class LinuxIsolation(Enum):
    LINUX_ISOLATION_UNSPECIFIED = 'LINUX_ISOLATION_UNSPECIFIED'
    GVISOR = 'GVISOR'
    OFF = 'OFF'


class MacExecution(Enum):
    MAC_EXECUTION_UNSPECIFIED = 'MAC_EXECUTION_UNSPECIFIED'
    MAC_EXECUTION_FORBIDDEN = 'MAC_EXECUTION_FORBIDDEN'


class VmVerification(Enum):
    VM_VERIFICATION_UNSPECIFIED = 'VM_VERIFICATION_UNSPECIFIED'
    VM_VERIFICATION_GCP_TOKEN = 'VM_VERIFICATION_GCP_TOKEN'
    VM_VERIFICATION_OFF = 'VM_VERIFICATION_OFF'


class WindowsExecution(Enum):
    WINDOWS_EXECUTION_UNSPECIFIED = 'WINDOWS_EXECUTION_UNSPECIFIED'
    WINDOWS_EXECUTION_FORBIDDEN = 'WINDOWS_EXECUTION_FORBIDDEN'
    WINDOWS_EXECUTION_UNRESTRICTED = 'WINDOWS_EXECUTION_UNRESTRICTED'
    WINDOWS_EXECUTION_TERMINAL = 'WINDOWS_EXECUTION_TERMINAL'


class Policy(Enum):
    POLICY_UNSPECIFIED = 'POLICY_UNSPECIFIED'
    ALLOWED = 'ALLOWED'
    FORBIDDEN = 'FORBIDDEN'
    RESTRICTED = 'RESTRICTED'


class GoogleDevtoolsRemotebuildexecutionAdminV1alphaFeaturePolicyFeature(BaseModel):
    allowedValues: Optional[List[str]] = Field(
        None,
        description='A list of acceptable values. Only effective when the policy is `RESTRICTED`.',
    )
    policy: Optional[Policy] = Field(None, description='The policy of the feature.')


class GoogleDevtoolsRemotebuildexecutionAdminV1alphaGetInstanceRequest(BaseModel):
    name: Optional[str] = Field(
        None,
        description='Required. Name of the instance to retrieve. Format: `projects/[PROJECT_ID]/instances/[INSTANCE_ID]`.',
    )


class GoogleDevtoolsRemotebuildexecutionAdminV1alphaGetWorkerPoolRequest(BaseModel):
    name: Optional[str] = Field(
        None,
        description='Name of the worker pool to retrieve. Format: `projects/[PROJECT_ID]/instances/[INSTANCE_ID]/workerpools/[POOL_ID]`.',
    )


class State(Enum):
    STATE_UNSPECIFIED = 'STATE_UNSPECIFIED'
    CREATING = 'CREATING'
    RUNNING = 'RUNNING'
    INACTIVE = 'INACTIVE'


class GoogleDevtoolsRemotebuildexecutionAdminV1alphaListInstancesRequest(BaseModel):
    parent: Optional[str] = Field(
        None,
        description='Required. Resource name of the project. Format: `projects/[PROJECT_ID]`.',
    )


class GoogleDevtoolsRemotebuildexecutionAdminV1alphaListWorkerPoolsRequest(BaseModel):
    filter: Optional[str] = Field(
        None,
        description='Optional. A filter expression that filters resources listed in the response. The expression must specify the field name, a comparison operator, and the value that you want to use for filtering. The value must be a string, a number, or a boolean. String values are case-insensitive. The comparison operator must be either `:`, `=`, `!=`, `>`, `>=`, `<=` or `<`. The `:` operator can be used with string fields to match substrings. For non-string fields it is equivalent to the `=` operator. The `:*` comparison can be used to test whether a key has been defined. You can also filter on nested fields. To filter on multiple expressions, you can separate expression using `AND` and `OR` operators, using parentheses to specify precedence. If neither operator is specified, `AND` is assumed. Examples: Include only pools with more than 100 reserved workers: `(worker_count > 100) (worker_config.reserved = true)` Include only pools with a certain label or machines of the e2-standard family: `worker_config.labels.key1 : * OR worker_config.machine_type: e2-standard`',
    )
    parent: Optional[str] = Field(
        None,
        description='Resource name of the instance. Format: `projects/[PROJECT_ID]/instances/[INSTANCE_ID]`.',
    )


class GoogleDevtoolsRemotebuildexecutionAdminV1alphaSchedulerNotificationConfig(
    BaseModel
):
    topic: Optional[str] = Field(
        None,
        description='The Pub/Sub topic resource name to issue notifications to. Note that the topic does not need to be owned by the same project as this instance. Format: `projects//topics/`.',
    )


class GoogleDevtoolsRemotebuildexecutionAdminV1alphaTestNotifyInstanceRequest(
    BaseModel
):
    pass


class GoogleDevtoolsRemotebuildexecutionAdminV1alphaWorkerConfig(BaseModel):
    accelerator: Optional[
        GoogleDevtoolsRemotebuildexecutionAdminV1alphaAcceleratorConfig
    ] = Field(None, description='The accelerator card attached to each VM.')
    diskSizeGb: Optional[str] = Field(
        None,
        description='Required. Size of the disk attached to the worker, in GB. See https://cloud.google.com/compute/docs/disks/',
    )
    diskType: Optional[str] = Field(
        None,
        description='Required. Disk Type to use for the worker. See [Storage options](https://cloud.google.com/compute/docs/disks/#introduction). Currently only `pd-standard` and `pd-ssd` are supported.',
    )
    labels: Optional[Dict[str, str]] = Field(
        None,
        description='Labels associated with the workers. Label keys and values can be no longer than 63 characters, can only contain lowercase letters, numeric characters, underscores and dashes. International letters are permitted. Label keys must start with a letter. Label values are optional. There can not be more than 64 labels per resource.',
    )
    machineType: Optional[str] = Field(
        None,
        description='Required. Machine type of the worker, such as `e2-standard-2`. See https://cloud.google.com/compute/docs/machine-types for a list of supported machine types. Note that `f1-micro` and `g1-small` are not yet supported.',
    )
    maxConcurrentActions: Optional[str] = Field(
        None,
        description='The maximum number of actions a worker can execute concurrently.',
    )
    minCpuPlatform: Optional[str] = Field(
        None,
        description='Minimum CPU platform to use when creating the worker. See [CPU Platforms](https://cloud.google.com/compute/docs/cpu-platforms).',
    )
    networkAccess: Optional[str] = Field(
        None,
        description='Determines the type of network access granted to workers. Possible values: - "public": Workers can connect to the public internet. - "private": Workers can only connect to Google APIs and services. - "restricted-private": Workers can only connect to Google APIs that are reachable through `restricted.googleapis.com` (`199.36.153.4/30`).',
    )
    reserved: Optional[bool] = Field(
        None,
        description="Determines whether the worker is reserved (equivalent to a Compute Engine on-demand VM and therefore won't be preempted). See [Preemptible VMs](https://cloud.google.com/preemptible-vms/) for more details.",
    )
    soleTenantNodeType: Optional[str] = Field(
        None, description='The node type name to be used for sole-tenant nodes.'
    )
    vmImage: Optional[str] = Field(
        None, description='The name of the image used by each VM.'
    )


class State1(Enum):
    STATE_UNSPECIFIED = 'STATE_UNSPECIFIED'
    CREATING = 'CREATING'
    RUNNING = 'RUNNING'
    UPDATING = 'UPDATING'
    DELETING = 'DELETING'
    INACTIVE = 'INACTIVE'


class GoogleDevtoolsRemotebuildexecutionAdminV1alphaWorkerPool(BaseModel):
    autoscale: Optional[GoogleDevtoolsRemotebuildexecutionAdminV1alphaAutoscale] = (
        Field(None, description='The autoscale policy to apply on a pool.')
    )
    channel: Optional[str] = Field(
        None, description='Channel specifies the release channel of the pool.'
    )
    hostOs: Optional[str] = Field(
        None,
        description='HostOS specifies the OS version of the image for the worker VMs.',
    )
    name: Optional[str] = Field(
        None,
        description='WorkerPool resource name formatted as: `projects/[PROJECT_ID]/instances/[INSTANCE_ID]/workerpools/[POOL_ID]`. name should not be populated when creating a worker pool since it is provided in the `poolId` field.',
    )
    state: Optional[State1] = Field(
        None, description='Output only. State of the worker pool.'
    )
    workerConfig: Optional[
        GoogleDevtoolsRemotebuildexecutionAdminV1alphaWorkerConfig
    ] = Field(
        None,
        description='Specifies the properties, such as machine type and disk size, used for creating workers in a worker pool.',
    )
    workerCount: Optional[str] = Field(
        None,
        description='The desired number of workers in the worker pool. Must be a value between 0 and 15000.',
    )


class Command(Enum):
    UNSPECIFIED = 'UNSPECIFIED'
    BOT_UPDATE = 'BOT_UPDATE'
    BOT_RESTART = 'BOT_RESTART'
    BOT_TERMINATE = 'BOT_TERMINATE'
    HOST_RESTART = 'HOST_RESTART'


class GoogleDevtoolsRemoteworkersV1test2AdminTemp(BaseModel):
    arg: Optional[str] = Field(
        None,
        description='The argument to the admin action; see `Command` for semantics.',
    )
    command: Optional[Command] = Field(
        None, description='The admin action; see `Command` for legal values.'
    )


class GoogleDevtoolsRemoteworkersV1test2CommandOverhead(BaseModel):
    duration: Optional[str] = Field(
        None,
        description='The elapsed time between calling Accept and Complete. The server will also have its own idea of what this should be, but this excludes the overhead of the RPCs and the bot response time.',
    )
    overhead: Optional[str] = Field(
        None,
        description='The amount of time *not* spent executing the command (ie uploading/downloading files).',
    )


class GoogleDevtoolsRemoteworkersV1test2CommandTaskInputsEnvironmentVariable(BaseModel):
    name: Optional[str] = Field(None, description='The envvar name.')
    value: Optional[str] = Field(None, description='The envvar value.')


class GoogleDevtoolsRemoteworkersV1test2CommandTaskOutputs(BaseModel):
    directories: Optional[List[str]] = Field(
        None,
        description='A list of expected directories, relative to the execution root. All paths MUST be delimited by forward slashes.',
    )
    files: Optional[List[str]] = Field(
        None,
        description='A list of expected files, relative to the execution root. All paths MUST be delimited by forward slashes.',
    )
    stderrDestination: Optional[str] = Field(
        None,
        description='The destination to which any stderr should be sent. The method by which the bot should send the stream contents to that destination is not defined in this API. As examples, the destination could be a file referenced in the `files` field in this message, or it could be a URI that must be written via the ByteStream API.',
    )
    stdoutDestination: Optional[str] = Field(
        None,
        description='The destination to which any stdout should be sent. The method by which the bot should send the stream contents to that destination is not defined in this API. As examples, the destination could be a file referenced in the `files` field in this message, or it could be a URI that must be written via the ByteStream API.',
    )


class GoogleDevtoolsRemoteworkersV1test2CommandTaskTimeouts(BaseModel):
    execution: Optional[str] = Field(
        None,
        description='This specifies the maximum time that the task can run, excluding the time required to download inputs or upload outputs. That is, the worker will terminate the task if it runs longer than this.',
    )
    idle: Optional[str] = Field(
        None,
        description='This specifies the maximum amount of time the task can be idle - that is, go without generating some output in either stdout or stderr. If the process is silent for more than the specified time, the worker will terminate the task.',
    )
    shutdown: Optional[str] = Field(
        None,
        description='If the execution or IO timeouts are exceeded, the worker will try to gracefully terminate the task and return any existing logs. However, tasks may be hard-frozen in which case this process will fail. This timeout specifies how long to wait for a terminated task to shut down gracefully (e.g. via SIGTERM) before we bring down the hammer (e.g. SIGKILL on *nix, CTRL_BREAK_EVENT on Windows).',
    )


class GoogleDevtoolsRemoteworkersV1test2Digest(BaseModel):
    hash: Optional[str] = Field(
        None,
        description='A string-encoded hash (eg "1a2b3c", not the byte array [0x1a, 0x2b, 0x3c]) using an implementation-defined hash algorithm (eg SHA-256).',
    )
    sizeBytes: Optional[str] = Field(
        None,
        description="The size of the contents. While this is not strictly required as part of an identifier (after all, any given hash will have exactly one canonical size), it's useful in almost all cases when one might want to send or retrieve blobs of content and is included here for this reason.",
    )


class GoogleDevtoolsRemoteworkersV1test2DirectoryMetadata(BaseModel):
    digest: Optional[GoogleDevtoolsRemoteworkersV1test2Digest] = Field(
        None,
        description='A pointer to the contents of the directory, in the form of a marshalled Directory message.',
    )
    path: Optional[str] = Field(
        None, description='The path of the directory, as in FileMetadata.path.'
    )


class GoogleDevtoolsRemoteworkersV1test2FileMetadata(BaseModel):
    contents: Optional[str] = Field(
        None,
        description='If the file is small enough, its contents may also or alternatively be listed here.',
    )
    digest: Optional[GoogleDevtoolsRemoteworkersV1test2Digest] = Field(
        None,
        description='A pointer to the contents of the file. The method by which a client retrieves the contents from a CAS system is not defined here.',
    )
    isExecutable: Optional[bool] = Field(None, description='Properties of the file')
    path: Optional[str] = Field(
        None,
        description='The path of this file. If this message is part of the CommandOutputs.outputs fields, the path is relative to the execution root and must correspond to an entry in CommandTask.outputs.files. If this message is part of a Directory message, then the path is relative to the root of that directory. All paths MUST be delimited by forward slashes.',
    )


class GoogleProtobufEmpty(BaseModel):
    pass


class GoogleRpcStatus(BaseModel):
    code: Optional[int] = Field(
        None,
        description='The status code, which should be an enum value of google.rpc.Code.',
    )
    details: Optional[List[Dict[str, Any]]] = Field(
        None,
        description='A list of messages that carry the error details. There is a common set of message types for APIs to use.',
    )
    message: Optional[str] = Field(
        None,
        description='A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the google.rpc.Status.details field, or localized by the client.',
    )


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class BuildBazelRemoteExecutionV2ExecuteOperationMetadata(BaseModel):
    actionDigest: Optional[BuildBazelRemoteExecutionV2Digest] = Field(
        None, description='The digest of the Action being executed.'
    )
    partialExecutionMetadata: Optional[
        BuildBazelRemoteExecutionV2ExecutedActionMetadata
    ] = Field(
        None,
        description='The client can read this field to view details about the ongoing execution.',
    )
    stage: Optional[Stage] = Field(None, description='The current stage of execution.')
    stderrStreamName: Optional[str] = Field(
        None,
        description='If set, the client can use this resource name with ByteStream.Read to stream the standard error from the endpoint hosting streamed responses.',
    )
    stdoutStreamName: Optional[str] = Field(
        None,
        description='If set, the client can use this resource name with ByteStream.Read to stream the standard output from the endpoint hosting streamed responses.',
    )


class BuildBazelRemoteExecutionV2NodeProperties(BaseModel):
    mtime: Optional[str] = Field(
        None, description="The file's last modification timestamp."
    )
    properties: Optional[List[BuildBazelRemoteExecutionV2NodeProperty]] = Field(
        None, description='A list of string-based NodeProperties.'
    )
    unixMode: Optional[int] = Field(None, description='The UNIX file mode, e.g., 0755.')


class BuildBazelRemoteExecutionV2OutputFile(BaseModel):
    contents: Optional[str] = Field(
        None,
        description='The contents of the file if inlining was requested. The server SHOULD NOT inline file contents unless requested by the client in the GetActionResultRequest message. The server MAY omit inlining, even if requested, and MUST do so if inlining would cause the response to exceed message size limits. Clients SHOULD NOT populate this field when uploading to the cache.',
    )
    digest: Optional[BuildBazelRemoteExecutionV2Digest] = Field(
        None, description="The digest of the file's content."
    )
    isExecutable: Optional[bool] = Field(
        None, description='True if file is executable, false otherwise.'
    )
    nodeProperties: Optional[BuildBazelRemoteExecutionV2NodeProperties] = None
    path: Optional[str] = Field(
        None,
        description='The full path of the file relative to the working directory, including the filename. The path separator is a forward slash `/`. Since this is a relative path, it MUST NOT begin with a leading forward slash.',
    )


class BuildBazelRemoteExecutionV2OutputSymlink(BaseModel):
    nodeProperties: Optional[BuildBazelRemoteExecutionV2NodeProperties] = None
    path: Optional[str] = Field(
        None,
        description='The full path of the symlink relative to the working directory, including the filename. The path separator is a forward slash `/`. Since this is a relative path, it MUST NOT begin with a leading forward slash.',
    )
    target: Optional[str] = Field(
        None,
        description='The target path of the symlink. The path separator is a forward slash `/`. The target path can be relative to the parent directory of the symlink or it can be an absolute path starting with `/`. Support for absolute paths can be checked using the Capabilities API. `..` components are allowed anywhere in the target path.',
    )


class BuildBazelRemoteExecutionV2Platform(BaseModel):
    properties: Optional[List[BuildBazelRemoteExecutionV2PlatformProperty]] = Field(
        None,
        description='The properties that make up this platform. In order to ensure that equivalent `Platform`s always hash to the same value, the properties MUST be lexicographically sorted by name, and then by value. Sorting of strings is done by code point, equivalently, by the UTF-8 bytes.',
    )


class BuildBazelRemoteExecutionV2RequestMetadata(BaseModel):
    actionId: Optional[str] = Field(
        None,
        description='An identifier that ties multiple requests to the same action. For example, multiple requests to the CAS, Action Cache, and Execution API are used in order to compile foo.cc.',
    )
    actionMnemonic: Optional[str] = Field(
        None,
        description='A brief description of the kind of action, for example, CppCompile or GoLink. There is no standard agreed set of values for this, and they are expected to vary between different client tools.',
    )
    configurationId: Optional[str] = Field(
        None,
        description='An identifier for the configuration in which the target was built, e.g. for differentiating building host tools or different target platforms. There is no expectation that this value will have any particular structure, or equality across invocations, though some client tools may offer these guarantees.',
    )
    correlatedInvocationsId: Optional[str] = Field(
        None,
        description='An identifier to tie multiple tool invocations together. For example, runs of foo_test, bar_test and baz_test on a post-submit of a given patch.',
    )
    targetId: Optional[str] = Field(
        None,
        description='An identifier for the target which produced this action. No guarantees are made around how many actions may relate to a single target.',
    )
    toolDetails: Optional[BuildBazelRemoteExecutionV2ToolDetails] = Field(
        None, description='The details for the tool invoking the requests.'
    )
    toolInvocationId: Optional[str] = Field(
        None,
        description='An identifier that ties multiple actions together to a final result. For example, multiple actions are required to build and run foo_test.',
    )


class BuildBazelRemoteExecutionV2SymlinkNode(BaseModel):
    name: Optional[str] = Field(None, description='The name of the symlink.')
    nodeProperties: Optional[BuildBazelRemoteExecutionV2NodeProperties] = None
    target: Optional[str] = Field(
        None,
        description='The target path of the symlink. The path separator is a forward slash `/`. The target path can be relative to the parent directory of the symlink or it can be an absolute path starting with `/`. Support for absolute paths can be checked using the Capabilities API. `..` components are allowed anywhere in the target path as logical canonicalization may lead to different behavior in the presence of directory symlinks (e.g. `foo/../bar` may not be the same as `bar`). To reduce potential cache misses, canonicalization is still recommended where this is possible without impacting correctness.',
    )


class GoogleDevtoolsRemotebuildbotResourceUsage(BaseModel):
    cpuUsedPercent: Optional[float] = None
    diskUsage: Optional[GoogleDevtoolsRemotebuildbotResourceUsageStat] = None
    memoryUsage: Optional[GoogleDevtoolsRemotebuildbotResourceUsageStat] = None
    totalDiskIoStats: Optional[GoogleDevtoolsRemotebuildbotResourceUsageIOStats] = None


class GoogleDevtoolsRemotebuildexecutionAdminV1alphaCreateWorkerPoolRequest(BaseModel):
    parent: Optional[str] = Field(
        None,
        description='Resource name of the instance in which to create the new worker pool. Format: `projects/[PROJECT_ID]/instances/[INSTANCE_ID]`.',
    )
    poolId: Optional[str] = Field(
        None,
        description='ID of the created worker pool. A valid pool ID must: be 6-50 characters long, contain only lowercase letters, digits, hyphens and underscores, start with a lowercase letter, and end with a lowercase letter or a digit.',
    )
    workerPool: Optional[GoogleDevtoolsRemotebuildexecutionAdminV1alphaWorkerPool] = (
        Field(
            None,
            description='Specifies the worker pool to create. The name in the worker pool, if specified, is ignored.',
        )
    )


class GoogleDevtoolsRemotebuildexecutionAdminV1alphaFeaturePolicy(BaseModel):
    actionHermeticity: Optional[ActionHermeticity] = Field(
        None,
        description='Defines the hermeticity policy for actions on this instance. DO NOT USE: Experimental / unlaunched feature.',
    )
    actionIsolation: Optional[ActionIsolation] = Field(
        None,
        description='Defines the isolation policy for actions on this instance. DO NOT USE: Experimental / unlaunched feature.',
    )
    containerImageSources: Optional[
        GoogleDevtoolsRemotebuildexecutionAdminV1alphaFeaturePolicyFeature
    ] = Field(
        None,
        description='Which container image sources are allowed. Currently only RBE-supported registry (gcr.io) is allowed. One can allow all repositories under a project or one specific repository only. E.g. container_image_sources { policy: RESTRICTED allowed_values: [ "gcr.io/project-foo", "gcr.io/project-bar/repo-baz", ] } will allow any repositories under "gcr.io/project-foo" plus the repository "gcr.io/project-bar/repo-baz". Default (UNSPECIFIED) is equivalent to any source is allowed.',
    )
    dockerAddCapabilities: Optional[
        GoogleDevtoolsRemotebuildexecutionAdminV1alphaFeaturePolicyFeature
    ] = Field(
        None,
        description='Whether dockerAddCapabilities can be used or what capabilities are allowed.',
    )
    dockerChrootPath: Optional[
        GoogleDevtoolsRemotebuildexecutionAdminV1alphaFeaturePolicyFeature
    ] = Field(None, description='Whether dockerChrootPath can be used.')
    dockerNetwork: Optional[
        GoogleDevtoolsRemotebuildexecutionAdminV1alphaFeaturePolicyFeature
    ] = Field(
        None,
        description='Whether dockerNetwork can be used or what network modes are allowed. E.g. one may allow `off` value only via `allowed_values`.',
    )
    dockerPrivileged: Optional[
        GoogleDevtoolsRemotebuildexecutionAdminV1alphaFeaturePolicyFeature
    ] = Field(None, description='Whether dockerPrivileged can be used.')
    dockerRunAsContainerProvidedUser: Optional[
        GoogleDevtoolsRemotebuildexecutionAdminV1alphaFeaturePolicyFeature
    ] = Field(None, description='Whether dockerRunAsContainerProvidedUser can be used.')
    dockerRunAsRoot: Optional[
        GoogleDevtoolsRemotebuildexecutionAdminV1alphaFeaturePolicyFeature
    ] = Field(None, description='Whether dockerRunAsRoot can be used.')
    dockerRuntime: Optional[
        GoogleDevtoolsRemotebuildexecutionAdminV1alphaFeaturePolicyFeature
    ] = Field(
        None,
        description='Whether dockerRuntime is allowed to be set or what runtimes are allowed. Note linux_isolation takes precedence, and if set, docker_runtime values may be rejected if they are incompatible with the selected isolation.',
    )
    dockerSiblingContainers: Optional[
        GoogleDevtoolsRemotebuildexecutionAdminV1alphaFeaturePolicyFeature
    ] = Field(None, description='Whether dockerSiblingContainers can be used.')
    linuxExecution: Optional[LinuxExecution] = Field(
        None,
        description='Defines how Linux actions are allowed to execute. DO NOT USE: Experimental / unlaunched feature.',
    )
    linuxIsolation: Optional[LinuxIsolation] = Field(
        None,
        description='linux_isolation allows overriding the docker runtime used for containers started on Linux.',
    )
    macExecution: Optional[MacExecution] = Field(
        None,
        description='Defines how Windows actions are allowed to execute. DO NOT USE: Experimental / unlaunched feature.',
    )
    vmVerification: Optional[VmVerification] = Field(
        None,
        description='Whether to verify CreateBotSession and UpdateBotSession from the bot.',
    )
    windowsExecution: Optional[WindowsExecution] = Field(
        None,
        description='Defines how Windows actions are allowed to execute. DO NOT USE: Experimental / unlaunched feature.',
    )


class GoogleDevtoolsRemotebuildexecutionAdminV1alphaInstance(BaseModel):
    featurePolicy: Optional[
        GoogleDevtoolsRemotebuildexecutionAdminV1alphaFeaturePolicy
    ] = Field(
        None,
        description='The policy to define whether or not RBE features can be used or how they can be used.',
    )
    location: Optional[str] = Field(
        None,
        description='The location is a GCP region. Currently only `us-central1` is supported.',
    )
    loggingEnabled: Optional[bool] = Field(
        None,
        description='Output only. Whether stack driver logging is enabled for the instance.',
    )
    name: Optional[str] = Field(
        None,
        description='Output only. Instance resource name formatted as: `projects/[PROJECT_ID]/instances/[INSTANCE_ID]`. Name should not be populated when creating an instance since it is provided in the `instance_id` field.',
    )
    schedulerNotificationConfig: Optional[
        GoogleDevtoolsRemotebuildexecutionAdminV1alphaSchedulerNotificationConfig
    ] = Field(
        None,
        description="The instance's configuration for scheduler notifications. Absence implies that this feature is not enabled for this instance.",
    )
    state: Optional[State] = Field(
        None, description='Output only. State of the instance.'
    )


class GoogleDevtoolsRemotebuildexecutionAdminV1alphaListInstancesResponse(BaseModel):
    instances: Optional[
        List[GoogleDevtoolsRemotebuildexecutionAdminV1alphaInstance]
    ] = Field(None, description='The list of instances in a given project.')
    unreachable: Optional[List[str]] = Field(None, description='Unreachable regions.')


class GoogleDevtoolsRemotebuildexecutionAdminV1alphaListWorkerPoolsResponse(BaseModel):
    workerPools: Optional[
        List[GoogleDevtoolsRemotebuildexecutionAdminV1alphaWorkerPool]
    ] = Field(None, description='The list of worker pools in a given instance.')


class GoogleDevtoolsRemotebuildexecutionAdminV1alphaUpdateInstanceRequest(BaseModel):
    instance: Optional[GoogleDevtoolsRemotebuildexecutionAdminV1alphaInstance] = Field(
        None, description='Specifies the instance to update.'
    )
    loggingEnabled: Optional[bool] = Field(
        None,
        description='Deprecated, use instance.logging_enabled instead. Whether to enable Stackdriver logging for this instance.',
    )
    name: Optional[str] = Field(
        None,
        description='Deprecated, use instance.Name instead. Name of the instance to update. Format: `projects/[PROJECT_ID]/instances/[INSTANCE_ID]`.',
    )
    updateMask: Optional[str] = Field(
        None,
        description='The update mask applies to instance. For the `FieldMask` definition, see https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#fieldmask If an empty update_mask is provided, only the non-default valued field in the worker pool field will be updated. Note that in order to update a field to the default value (zero, false, empty string) an explicit update_mask must be provided.',
    )


class GoogleDevtoolsRemotebuildexecutionAdminV1alphaUpdateWorkerPoolRequest(BaseModel):
    updateMask: Optional[str] = Field(
        None,
        description='The update mask applies to worker_pool. For the `FieldMask` definition, see https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#fieldmask If an empty update_mask is provided, only the non-default valued field in the worker pool field will be updated. Note that in order to update a field to the default value (zero, false, empty string) an explicit update_mask must be provided.',
    )
    workerPool: Optional[GoogleDevtoolsRemotebuildexecutionAdminV1alphaWorkerPool] = (
        Field(None, description='Specifies the worker pool to update.')
    )


class GoogleDevtoolsRemoteworkersV1test2Blob(BaseModel):
    contents: Optional[str] = Field(None, description='The contents of the blob.')
    digest: Optional[GoogleDevtoolsRemoteworkersV1test2Digest] = Field(
        None,
        description='The digest of the blob. This should be verified by the receiver.',
    )


class GoogleDevtoolsRemoteworkersV1test2CommandOutputs(BaseModel):
    exitCode: Optional[int] = Field(
        None,
        description="exit_code is only fully reliable if the status' code is OK. If the task exceeded its deadline or was cancelled, the process may still produce an exit code as it is cancelled, and this will be populated, but a successful (zero) is unlikely to be correct unless the status code is OK.",
    )
    outputs: Optional[GoogleDevtoolsRemoteworkersV1test2Digest] = Field(
        None,
        description='The output files. The blob referenced by the digest should contain one of the following (implementation-dependent): * A marshalled DirectoryMetadata of the returned filesystem * A LUCI-style .isolated file',
    )


class GoogleDevtoolsRemoteworkersV1test2CommandResult(BaseModel):
    duration: Optional[str] = Field(
        None,
        description='The elapsed time between calling Accept and Complete. The server will also have its own idea of what this should be, but this excludes the overhead of the RPCs and the bot response time.',
    )
    exitCode: Optional[int] = Field(
        None,
        description='The exit code of the process. An exit code of "0" should only be trusted if `status` has a code of OK (otherwise it may simply be unset).',
    )
    metadata: Optional[List[Dict[str, Any]]] = Field(
        None,
        description="Implementation-dependent metadata about the task. Both servers and bots may define messages which can be encoded here; bots are free to provide metadata in multiple formats, and servers are free to choose one or more of the values to process and ignore others. In particular, it is *not* considered an error for the bot to provide the server with a field that it doesn't know about.",
    )
    outputs: Optional[GoogleDevtoolsRemoteworkersV1test2Digest] = Field(
        None,
        description='The output files. The blob referenced by the digest should contain one of the following (implementation-dependent): * A marshalled DirectoryMetadata of the returned filesystem * A LUCI-style .isolated file',
    )
    overhead: Optional[str] = Field(
        None,
        description='The amount of time *not* spent executing the command (ie uploading/downloading files).',
    )
    status: Optional[GoogleRpcStatus] = Field(
        None,
        description='An overall status for the command. For example, if the command timed out, this might have a code of DEADLINE_EXCEEDED; if it was killed by the OS for memory exhaustion, it might have a code of RESOURCE_EXHAUSTED.',
    )


class GoogleDevtoolsRemoteworkersV1test2CommandTaskInputs(BaseModel):
    arguments: Optional[List[str]] = Field(
        None,
        description='The command itself to run (e.g., argv). This field should be passed directly to the underlying operating system, and so it must be sensible to that operating system. For example, on Windows, the first argument might be "C:\\Windows\\System32\\ping.exe" - that is, using drive letters and backslashes. A command for a *nix system, on the other hand, would use forward slashes. All other fields in the RWAPI must consistently use forward slashes, since those fields may be interpretted by both the service and the bot.',
    )
    environmentVariables: Optional[
        List[GoogleDevtoolsRemoteworkersV1test2CommandTaskInputsEnvironmentVariable]
    ] = Field(None, description='All environment variables required by the task.')
    files: Optional[List[GoogleDevtoolsRemoteworkersV1test2Digest]] = Field(
        None,
        description="The input filesystem to be set up prior to the task beginning. The contents should be a repeated set of FileMetadata messages though other formats are allowed if better for the implementation (eg, a LUCI-style .isolated file). This field is repeated since implementations might want to cache the metadata, in which case it may be useful to break up portions of the filesystem that change frequently (eg, specific input files) from those that don't (eg, standard header files).",
    )
    inlineBlobs: Optional[List[GoogleDevtoolsRemoteworkersV1test2Blob]] = Field(
        None,
        description='Inline contents for blobs expected to be needed by the bot to execute the task. For example, contents of entries in `files` or blobs that are indirectly referenced by an entry there. The bot should check against this list before downloading required task inputs to reduce the number of communications between itself and the remote CAS server.',
    )
    workingDirectory: Optional[str] = Field(
        None,
        description='Directory from which a command is executed. It is a relative directory with respect to the bot\'s working directory (i.e., "./"). If it is non-empty, then it must exist under "./". Otherwise, "./" will be used.',
    )


class GoogleDevtoolsRemoteworkersV1test2Directory(BaseModel):
    directories: Optional[List[GoogleDevtoolsRemoteworkersV1test2DirectoryMetadata]] = (
        Field(None, description='Any subdirectories')
    )
    files: Optional[List[GoogleDevtoolsRemoteworkersV1test2FileMetadata]] = Field(
        None, description='The files in this directory'
    )


class GoogleLongrunningOperation(BaseModel):
    done: Optional[bool] = Field(
        None,
        description='If the value is `false`, it means the operation is still in progress. If `true`, the operation is completed, and either `error` or `response` is available.',
    )
    error: Optional[GoogleRpcStatus] = Field(
        None,
        description='The error result of the operation in case of failure or cancellation.',
    )
    metadata: Optional[Dict[str, Any]] = Field(
        None,
        description='Service-specific metadata associated with the operation. It typically contains progress information and common metadata such as create time. Some services might not provide such metadata. Any method that returns a long-running operation should document the metadata type, if any.',
    )
    name: Optional[str] = Field(
        None,
        description='The server-assigned name, which is only unique within the same service that originally returns it. If you use the default HTTP mapping, the `name` should be a resource name ending with `operations/{unique_id}`.',
    )
    response: Optional[Dict[str, Any]] = Field(
        None,
        description='The normal response of the operation in case of success. If the original method returns no data on success, such as `Delete`, the response is `google.protobuf.Empty`. If the original method is standard `Get`/`Create`/`Update`, the response should be the resource. For other methods, the response should have the type `XxxResponse`, where `Xxx` is the original method name. For example, if the original method name is `TakeSnapshot()`, the inferred response type is `TakeSnapshotResponse`.',
    )


class BuildBazelRemoteExecutionV2Action(BaseModel):
    commandDigest: Optional[BuildBazelRemoteExecutionV2Digest] = Field(
        None,
        description='The digest of the Command to run, which MUST be present in the ContentAddressableStorage.',
    )
    doNotCache: Optional[bool] = Field(
        None,
        description="If true, then the `Action`'s result cannot be cached, and in-flight requests for the same `Action` may not be merged.",
    )
    inputRootDigest: Optional[BuildBazelRemoteExecutionV2Digest] = Field(
        None,
        description='The digest of the root Directory for the input files. The files in the directory tree are available in the correct location on the build machine before the command is executed. The root directory, as well as every subdirectory and content blob referred to, MUST be in the ContentAddressableStorage.',
    )
    platform: Optional[BuildBazelRemoteExecutionV2Platform] = Field(
        None,
        description='The optional platform requirements for the execution environment. The server MAY choose to execute the action on any worker satisfying the requirements, so the client SHOULD ensure that running the action on any such worker will have the same result. A detailed lexicon for this can be found in the accompanying platform.md. New in version 2.2: clients SHOULD set these platform properties as well as those in the Command. Servers SHOULD prefer those set here.',
    )
    salt: Optional[str] = Field(
        None,
        description='An optional additional salt value used to place this `Action` into a separate cache namespace from other instances having the same field contents. This salt typically comes from operational configuration specific to sources such as repo and service configuration, and allows disowning an entire set of ActionResults that might have been poisoned by buggy software or tool failures.',
    )
    timeout: Optional[str] = Field(
        None,
        description='A timeout after which the execution should be killed. If the timeout is absent, then the client is specifying that the execution should continue as long as the server will let it. The server SHOULD impose a timeout if the client does not specify one, however, if the client does specify a timeout that is longer than the server\'s maximum timeout, the server MUST reject the request. The timeout is only intended to cover the "execution" of the specified action and not time in queue nor any overheads before or after execution such as marshalling inputs/outputs. The server SHOULD avoid including time spent the client doesn\'t have control over, and MAY extend or reduce the timeout to account for delays or speedups that occur during execution itself (e.g., lazily loading data from the Content Addressable Storage, live migration of virtual machines, emulation overhead). The timeout is a part of the Action message, and therefore two `Actions` with different timeouts are different, even if they are otherwise identical. This is because, if they were not, running an `Action` with a lower timeout than is required might result in a cache hit from an execution run with a longer timeout, hiding the fact that the timeout is too short. By encoding it directly in the `Action`, a lower timeout will result in a cache miss and the execution timeout will fail immediately, rather than whenever the cache entry gets evicted.',
    )


class BuildBazelRemoteExecutionV2ActionResult(BaseModel):
    executionMetadata: Optional[BuildBazelRemoteExecutionV2ExecutedActionMetadata] = (
        Field(
            None,
            description='The details of the execution that originally produced this result.',
        )
    )
    exitCode: Optional[int] = Field(None, description='The exit code of the command.')
    outputDirectories: Optional[List[BuildBazelRemoteExecutionV2OutputDirectory]] = (
        Field(
            None,
            description='The output directories of the action. For each output directory requested in the `output_directories` or `output_paths` field of the Action, if the corresponding directory existed after the action completed, a single entry will be present in the output list, which will contain the digest of a Tree message containing the directory tree, and the path equal exactly to the corresponding Action output_directories member. As an example, suppose the Action had an output directory `a/b/dir` and the execution produced the following contents in `a/b/dir`: a file named `bar` and a directory named `foo` with an executable file named `baz`. Then, output_directory will contain (hashes shortened for readability): ```json // OutputDirectory proto: { path: "a/b/dir" tree_digest: { hash: "4a73bc9d03...", size: 55 } } // Tree proto with hash "4a73bc9d03..." and size 55: { root: { files: [ { name: "bar", digest: { hash: "4a73bc9d03...", size: 65534 } } ], directories: [ { name: "foo", digest: { hash: "4cf2eda940...", size: 43 } } ] } children : { // (Directory proto with hash "4cf2eda940..." and size 43) files: [ { name: "baz", digest: { hash: "b2c941073e...", size: 1294, }, is_executable: true } ] } } ``` If an output of the same name as listed in `output_files` of the Command was found in `output_directories`, but was not a directory, the server will return a FAILED_PRECONDITION.',
        )
    )
    outputDirectorySymlinks: Optional[
        List[BuildBazelRemoteExecutionV2OutputSymlink]
    ] = Field(
        None,
        description='The output directories of the action that are symbolic links to other directories. Those may be links to other output directories, or input directories, or even absolute paths outside of the working directory, if the server supports SymlinkAbsolutePathStrategy.ALLOWED. For each output directory requested in the `output_directories` field of the Action, if the directory existed after the action completed, a single entry will be present either in this field, or in the `output_directories` field, if the directory was not a symbolic link. If an output of the same name was found, but was a symbolic link to a file instead of a directory, the server will return a FAILED_PRECONDITION. If the action does not produce the requested output, then that output will be omitted from the list. The server is free to arrange the output list as desired; clients MUST NOT assume that the output list is sorted. DEPRECATED as of v2.1. Servers that wish to be compatible with v2.0 API should still populate this field in addition to `output_symlinks`.',
    )
    outputFileSymlinks: Optional[List[BuildBazelRemoteExecutionV2OutputSymlink]] = (
        Field(
            None,
            description='The output files of the action that are symbolic links to other files. Those may be links to other output files, or input files, or even absolute paths outside of the working directory, if the server supports SymlinkAbsolutePathStrategy.ALLOWED. For each output file requested in the `output_files` or `output_paths` field of the Action, if the corresponding file existed after the action completed, a single entry will be present either in this field, or in the `output_files` field, if the file was not a symbolic link. If an output symbolic link of the same name as listed in `output_files` of the Command was found, but its target type was not a regular file, the server will return a FAILED_PRECONDITION. If the action does not produce the requested output, then that output will be omitted from the list. The server is free to arrange the output list as desired; clients MUST NOT assume that the output list is sorted. DEPRECATED as of v2.1. Servers that wish to be compatible with v2.0 API should still populate this field in addition to `output_symlinks`.',
        )
    )
    outputFiles: Optional[List[BuildBazelRemoteExecutionV2OutputFile]] = Field(
        None,
        description='The output files of the action. For each output file requested in the `output_files` or `output_paths` field of the Action, if the corresponding file existed after the action completed, a single entry will be present either in this field, or the `output_file_symlinks` field if the file was a symbolic link to another file (`output_symlinks` field after v2.1). If an output listed in `output_files` was found, but was a directory rather than a regular file, the server will return a FAILED_PRECONDITION. If the action does not produce the requested output, then that output will be omitted from the list. The server is free to arrange the output list as desired; clients MUST NOT assume that the output list is sorted.',
    )
    outputSymlinks: Optional[List[BuildBazelRemoteExecutionV2OutputSymlink]] = Field(
        None,
        description='New in v2.1: this field will only be populated if the command `output_paths` field was used, and not the pre v2.1 `output_files` or `output_directories` fields. The output paths of the action that are symbolic links to other paths. Those may be links to other outputs, or inputs, or even absolute paths outside of the working directory, if the server supports SymlinkAbsolutePathStrategy.ALLOWED. A single entry for each output requested in `output_paths` field of the Action, if the corresponding path existed after the action completed and was a symbolic link. If the action does not produce a requested output, then that output will be omitted from the list. The server is free to arrange the output list as desired; clients MUST NOT assume that the output list is sorted.',
    )
    stderrDigest: Optional[BuildBazelRemoteExecutionV2Digest] = Field(
        None,
        description='The digest for a blob containing the standard error of the action, which can be retrieved from the ContentAddressableStorage.',
    )
    stderrRaw: Optional[str] = Field(
        None,
        description='The standard error buffer of the action. The server SHOULD NOT inline stderr unless requested by the client in the GetActionResultRequest message. The server MAY omit inlining, even if requested, and MUST do so if inlining would cause the response to exceed message size limits. Clients SHOULD NOT populate this field when uploading to the cache.',
    )
    stdoutDigest: Optional[BuildBazelRemoteExecutionV2Digest] = Field(
        None,
        description='The digest for a blob containing the standard output of the action, which can be retrieved from the ContentAddressableStorage.',
    )
    stdoutRaw: Optional[str] = Field(
        None,
        description='The standard output buffer of the action. The server SHOULD NOT inline stdout unless requested by the client in the GetActionResultRequest message. The server MAY omit inlining, even if requested, and MUST do so if inlining would cause the response to exceed message size limits. Clients SHOULD NOT populate this field when uploading to the cache.',
    )


class BuildBazelRemoteExecutionV2Command(BaseModel):
    arguments: Optional[List[str]] = Field(
        None,
        description="The arguments to the command. The first argument specifies the command to run, which may be either an absolute path, a path relative to the working directory, or an unqualified path (without path separators) which will be resolved using the operating system's equivalent of the PATH environment variable. Path separators native to the operating system running on the worker SHOULD be used. If the `environment_variables` list contains an entry for the PATH environment variable, it SHOULD be respected. If not, the resolution process is implementation-defined. Changed in v2.3. v2.2 and older require that no PATH lookups are performed, and that relative paths are resolved relative to the input root. This behavior can, however, not be relied upon, as most implementations already followed the rules described above.",
    )
    environmentVariables: Optional[
        List[BuildBazelRemoteExecutionV2CommandEnvironmentVariable]
    ] = Field(
        None,
        description='The environment variables to set when running the program. The worker may provide its own default environment variables; these defaults can be overridden using this field. Additional variables can also be specified. In order to ensure that equivalent Commands always hash to the same value, the environment variables MUST be lexicographically sorted by name. Sorting of strings is done by code point, equivalently, by the UTF-8 bytes.',
    )
    outputDirectories: Optional[List[str]] = Field(
        None,
        description='A list of the output directories that the client expects to retrieve from the action. Only the listed directories will be returned (an entire directory structure will be returned as a Tree message digest, see OutputDirectory), as well as files listed in `output_files`. Other files or directories that may be created during command execution are discarded. The paths are relative to the working directory of the action execution. The paths are specified using a single forward slash (`/`) as a path separator, even if the execution platform natively uses a different separator. The path MUST NOT include a trailing slash, nor a leading slash, being a relative path. The special value of empty string is allowed, although not recommended, and can be used to capture the entire working directory tree, including inputs. In order to ensure consistent hashing of the same Action, the output paths MUST be sorted lexicographically by code point (or, equivalently, by UTF-8 bytes). An output directory cannot be duplicated or have the same path as any of the listed output files. An output directory is allowed to be a parent of another output directory. Directories leading up to the output directories (but not the output directories themselves) are created by the worker prior to execution, even if they are not explicitly part of the input root. DEPRECATED since 2.1: Use `output_paths` instead.',
    )
    outputFiles: Optional[List[str]] = Field(
        None,
        description='A list of the output files that the client expects to retrieve from the action. Only the listed files, as well as directories listed in `output_directories`, will be returned to the client as output. Other files or directories that may be created during command execution are discarded. The paths are relative to the working directory of the action execution. The paths are specified using a single forward slash (`/`) as a path separator, even if the execution platform natively uses a different separator. The path MUST NOT include a trailing slash, nor a leading slash, being a relative path. In order to ensure consistent hashing of the same Action, the output paths MUST be sorted lexicographically by code point (or, equivalently, by UTF-8 bytes). An output file cannot be duplicated, be a parent of another output file, or have the same path as any of the listed output directories. Directories leading up to the output files are created by the worker prior to execution, even if they are not explicitly part of the input root. DEPRECATED since v2.1: Use `output_paths` instead.',
    )
    outputNodeProperties: Optional[List[str]] = Field(
        None,
        description='A list of keys for node properties the client expects to retrieve for output files and directories. Keys are either names of string-based NodeProperty or names of fields in NodeProperties. In order to ensure that equivalent `Action`s always hash to the same value, the node properties MUST be lexicographically sorted by name. Sorting of strings is done by code point, equivalently, by the UTF-8 bytes. The interpretation of string-based properties is server-dependent. If a property is not recognized by the server, the server will return an `INVALID_ARGUMENT`.',
    )
    outputPaths: Optional[List[str]] = Field(
        None,
        description='A list of the output paths that the client expects to retrieve from the action. Only the listed paths will be returned to the client as output. The type of the output (file or directory) is not specified, and will be determined by the server after action execution. If the resulting path is a file, it will be returned in an OutputFile typed field. If the path is a directory, the entire directory structure will be returned as a Tree message digest, see OutputDirectory Other files or directories that may be created during command execution are discarded. The paths are relative to the working directory of the action execution. The paths are specified using a single forward slash (`/`) as a path separator, even if the execution platform natively uses a different separator. The path MUST NOT include a trailing slash, nor a leading slash, being a relative path. In order to ensure consistent hashing of the same Action, the output paths MUST be deduplicated and sorted lexicographically by code point (or, equivalently, by UTF-8 bytes). Directories leading up to the output paths are created by the worker prior to execution, even if they are not explicitly part of the input root. New in v2.1: this field supersedes the DEPRECATED `output_files` and `output_directories` fields. If `output_paths` is used, `output_files` and `output_directories` will be ignored!',
    )
    platform: Optional[BuildBazelRemoteExecutionV2Platform] = Field(
        None,
        description='The platform requirements for the execution environment. The server MAY choose to execute the action on any worker satisfying the requirements, so the client SHOULD ensure that running the action on any such worker will have the same result. A detailed lexicon for this can be found in the accompanying platform.md. DEPRECATED as of v2.2: platform properties are now specified directly in the action. See documentation note in the Action for migration.',
    )
    workingDirectory: Optional[str] = Field(
        None,
        description='The working directory, relative to the input root, for the command to run in. It must be a directory which exists in the input tree. If it is left empty, then the action is run in the input root.',
    )


class BuildBazelRemoteExecutionV2ExecuteResponse(BaseModel):
    cachedResult: Optional[bool] = Field(
        None,
        description='True if the result was served from cache, false if it was executed.',
    )
    message: Optional[str] = Field(
        None,
        description='Freeform informational message with details on the execution of the action that may be displayed to the user upon failure or when requested explicitly.',
    )
    result: Optional[BuildBazelRemoteExecutionV2ActionResult] = Field(
        None, description='The result of the action.'
    )
    serverLogs: Optional[Dict[str, BuildBazelRemoteExecutionV2LogFile]] = Field(
        None,
        description="An optional list of additional log outputs the server wishes to provide. A server can use this to return execution-specific logs however it wishes. This is intended primarily to make it easier for users to debug issues that may be outside of the actual job execution, such as by identifying the worker executing the action or by providing logs from the worker's setup phase. The keys SHOULD be human readable so that a client can display them to a user.",
    )
    status: Optional[GoogleRpcStatus] = Field(
        None,
        description='If the status has a code other than `OK`, it indicates that the action did not finish execution. For example, if the operation times out during execution, the status will have a `DEADLINE_EXCEEDED` code. Servers MUST use this field for errors in execution, rather than the error field on the `Operation` object. If the status code is other than `OK`, then the result MUST NOT be cached. For an error status, the `result` field is optional; the server may populate the output-, stdout-, and stderr-related fields if it has any information available, such as the stdout and stderr of a timed-out action.',
    )


class BuildBazelRemoteExecutionV2FileNode(BaseModel):
    digest: Optional[BuildBazelRemoteExecutionV2Digest] = Field(
        None, description="The digest of the file's content."
    )
    isExecutable: Optional[bool] = Field(
        None, description='True if file is executable, false otherwise.'
    )
    name: Optional[str] = Field(None, description='The name of the file.')
    nodeProperties: Optional[BuildBazelRemoteExecutionV2NodeProperties] = None


class GoogleDevtoolsRemotebuildexecutionAdminV1alphaCreateInstanceRequest(BaseModel):
    instance: Optional[GoogleDevtoolsRemotebuildexecutionAdminV1alphaInstance] = Field(
        None,
        description='Required. Specifies the instance to create. The name in the instance, if specified in the instance, is ignored.',
    )
    instanceId: Optional[str] = Field(
        None,
        description='Required. ID of the created instance. A valid `instance_id` must: be 6-50 characters long, contain only lowercase letters, digits, hyphens and underscores, start with a lowercase letter, and end with a lowercase letter or a digit.',
    )
    parent: Optional[str] = Field(
        None,
        description='Required. Resource name of the project containing the instance. Format: `projects/[PROJECT_ID]`.',
    )


class GoogleDevtoolsRemoteworkersV1test2CommandTask(BaseModel):
    expectedOutputs: Optional[GoogleDevtoolsRemoteworkersV1test2CommandTaskOutputs] = (
        Field(None, description='The expected outputs from the task.')
    )
    inputs: Optional[GoogleDevtoolsRemoteworkersV1test2CommandTaskInputs] = Field(
        None, description='The inputs to the task.'
    )
    timeouts: Optional[GoogleDevtoolsRemoteworkersV1test2CommandTaskTimeouts] = Field(
        None, description='The timeouts of this task.'
    )


class BuildBazelRemoteExecutionV2Directory(BaseModel):
    directories: Optional[List[BuildBazelRemoteExecutionV2DirectoryNode]] = Field(
        None, description='The subdirectories in the directory.'
    )
    files: Optional[List[BuildBazelRemoteExecutionV2FileNode]] = Field(
        None, description='The files in the directory.'
    )
    nodeProperties: Optional[BuildBazelRemoteExecutionV2NodeProperties] = None
    symlinks: Optional[List[BuildBazelRemoteExecutionV2SymlinkNode]] = Field(
        None, description='The symlinks in the directory.'
    )


class BuildBazelRemoteExecutionV2Tree(BaseModel):
    children: Optional[List[BuildBazelRemoteExecutionV2Directory]] = Field(
        None,
        description='All the child directories: the directories referred to by the root and, recursively, all its children. In order to reconstruct the directory tree, the client must take the digests of each of the child directories and then build up a tree starting from the `root`. Servers SHOULD ensure that these are ordered consistently such that two actions producing equivalent output directories on the same server implementation also produce Tree messages with matching digests.',
    )
    root: Optional[BuildBazelRemoteExecutionV2Directory] = Field(
        None, description='The root directory in the tree.'
    )
